version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: ps
    environment: 
      POTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "7777:5432"
    volumes:
      - ps_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  ps_data:

networks:
  app_network:
    driver: bridge

